# Generated by the tokenmaxxing release workflow (packaging/tokenmaxxing.rb).
cask "tokenmaxxing" do
  version "$VERSION"
  sha256 "$SHA"

  url "https://github.com/HansKristoffer/tokenmaxxing/releases/download/v#{version}/Tokenmaxxing_#{version}_universal.dmg"
  name "Tokenmaxxing"
  desc "Pixel town for people who run AI coding agents"
  homepage "https://github.com/HansKristoffer/tokenmaxxing"

  # The app updates itself (Tauri's updater), so `brew upgrade` leaves it alone.
  auto_updates true
  depends_on macos: :sonoma

  app "Tokenmaxxing.app"

  uninstall quit: "dk.hanskristoffer.tokenmaxxing"

  zap trash: [
    "~/Library/Application Support/Tokenmaxxing",
    "~/Library/Logs/Tokenmaxxing",
    "~/Library/Logs/dk.hanskristoffer.tokenmaxxing",
    "~/Library/Caches/dk.hanskristoffer.tokenmaxxing",
    "~/Library/WebKit/dk.hanskristoffer.tokenmaxxing",
    "~/Library/LaunchAgents/Tokenmaxxing.plist",
    "~/Library/Preferences/dk.hanskristoffer.tokenmaxxing.plist",
  ]
end
